Add new Python test dependencies to dbuild
scylladb/scylla pull request #10397
Opened 2022-04-19 13:44 UTC by kostja

In order to see that the new tests pass dbuild at all, one must first dbuild dependencies which appear in test.py.v3 branch.

2022-04-19 13:48 UTC, avikivity commented
Please squash the two install-dependency patches, the procedure requires one image generation per patch, and I'd rather avoid generating them for no reason.

2022-04-19 14:01 UTC, nyh requested changes

2022-04-19 14:01 UTC, nyh commented on .gitignore
> +.mypy_cache
‎This change seems unrelated to this series, and is also included in a different series that you sent for review.

2022-04-20 14:17 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/126/

2022-04-22 12:23 UTC, closed without merging