cql3: refactor of native types parsing
scylladb/scylla pull request #10960
Opened 2022-07-04 14:24 UTC by margdoc

Native types were parsed directly to data_type, where varchar and text were
parsed to utf8_type. To get the name of the type there was a call to
the data_type method thus getting the name of varchar type returns "text".

To fix this, native types are parsed to native_type_token enum and then it
can be mapped to data_type or type name.

Fixes: #10642

2022-07-04 14:37 UTC, kbr- commented
Does this change have any other side effects we should be aware of?

The parser was going through `data_type` constructor when parsing the `K_VARCHAR` token in order to get its string representation. For `K_VARCHAR`, `utf8_type` was used, hence we got the `text` string.
Now we go directly from `K_VARCHAR` to `"varchar"`.
So every instance where the parser would parse `varchar`, it would change it to `text`.

In what other contexts other than table names will this commit change the behavior of the parser? Where else was the `native_type` grammar used like that?

2022-07-04 17:11 UTC, scylladb-promoter commented
CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/1161/

2022-07-04 18:06 UTC, nyh commented
There are a lot of failed tests in the CI run, some of them directly related to types, so please look at them.

2022-07-04 18:25 UTC, nyh requested changes
@margdoc I'll look at the details of your patch in a few minutes, trying to find the bugs that the tests found by failing, but just looking at the size of the patch, I think there is a simpler way to fix this:

The bug was caused because a table name in the parser can be an `unreserved_keyword` and that maps to the wrong string. Why? Because `unreserved_keyword` is defined as:
```
unreserved_keyword returns [sstring str]
    : u=unreserved_function_keyword     { $str = u; }
    | k=(K_TTL | K_COUNT | K_WRITETIME | K_KEY) { $str = $k.text; }
    ;

unreserved_function_keyword returns [sstring str]
    : u=basic_unreserved_keyword { $str = u; }
    | t=native_or_internal_type[true]   { $str = t->as_cql3_type().to_string(); }
```

I think it was a mistake to use "native_or_internal_type" here. We already have a long list of keywords in `basic_unreserved_keyword`. The easiest fix, proabably a 10-line patch, would be to drop the second line from `unreserved_function_keyword` and just add them to the list in `basic_unreserved_keyword`.

You can argue that this way there is duplication, we need to list those types twice - once in `basic_unreserved_keyword` and once in `native_type`, but:
1. Your patch also duplicates the same keywords, and makes them more complex.
2. `basic_unreserved_keywords` is already a very long list duplicating almost everything mentioned elsewhere in the parser.
3. We don't expect to add any more types soon anyway.

I really think that my recommended approach will result in a smaller patch, and one that doesn't break the tests. Can you please try?

Finally, I want to ask that you write a regression test for the issue you are fixing (https://github.com/scylladb/scylla/issues/10642) - i.e., a test which fails before your patch, and passes afterwards. I recommend that you use use either the test/cql-pytest framework (my favorite) or test/cql framework (@kostja's favorite).

2022-07-04 18:34 UTC, nyh commented
@margdoc I was too optimistic, we do need to separate type keywords from other keywords for non_type_ident, but I think the following patch will work (it compiles, but I didn't run all the tests, and didn't write a new test):

```patch
diff --git a/cql3/Cql.g b/cql3/Cql.g
index fabc7c497..b4c2e849c 100644
--- a/cql3/Cql.g
+++ b/cql3/Cql.g
@@ -1859,7 +1859,7 @@ unreserved_keyword returns [sstring str]
 
 unreserved_function_keyword returns [sstring str]
     : u=basic_unreserved_keyword { $str = u; }
-    | t=native_or_internal_type[true]   { $str = t->as_cql3_type().to_string(); }
+    | u=type_unreserved_keyword { $str = u; }
     ;
 
 basic_unreserved_keyword returns [sstring str]
@@ -1926,6 +1926,32 @@ basic_unreserved_keyword returns [sstring str]
         ) { $str = $k.text; }
     ;
 
+type_unreserved_keyword returns [sstring str]
+    : k=( K_ASCII
+        | K_BIGINT
+        | K_BLOB
+        | K_BOOLEAN
+        | K_COUNTER
+        | K_DECIMAL
+        | K_DOUBLE
+        | K_DURATION
+        | K_FLOAT
+        | K_INET
+        | K_INT
+        | K_SMALLINT
+        | K_TEXT
+        | K_TIMESTAMP
+        | K_TINYINT
+        | K_UUID
+        | K_VARCHAR
+        | K_VARINT
+        | K_TIMEUUID
+        | K_DATE
+        | K_TIME
+        | K_EMPTY
+        ) { $str = $k.text; }
+    ;
+
```

2022-07-05 08:57 UTC, margdoc commented
v2:
* add a regression test ```varchar_as_table_name_test```
* apply @nyh patch

2022-07-05 08:57 UTC, kbr- commented on test/cql/varchar_as_table_name_test.cql
> +CREATE KEYSPACE reproducer WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
Please add a comment explaining that this is a regression test for #10642. Simple e.g.
```
-- regression test for #10642
```

2022-07-05 09:01 UTC, kbr- commented
With the new version my questions are still relevant:
1.
> In what other contexts other than table names will this commit change the behavior of the parser? Where else was the native_type nonterminal used like that?

2. the question about lowercase/uppercase
3. different handling of `K_EMPTY`

2022-07-05 09:22 UTC, kbr- commented
Also the commit message and the PR cover letter need to be updated - they still describe the previous solution

2022-07-05 09:36 UTC, kbr- commented
> It will also impact on parsing keyspaces names, usernames, indexes names, so it shouldn't break anything

So do I understand correctly:
1. if someone creates a keyspace with name `varchar`, it will instead be created with name `text`
2. the same will happen when creating indexes
3. and the same will happen when creating usernames

In that case - please explain all of this in the commit message.

> Names passed to cf_name::set_column_family are lowercased now

OK, so the uppercasing won't matter for table names. But what of the other cases mentioned above? I.e. are indexes, usernames and keyspace names also lowercased later?

2022-07-05 10:21 UTC, margdoc commented
> So do I understand correctly:
    1. if someone creates a keyspace with name varchar, it will instead be created with name text
    2. the same will happen when creating indexes
    3. and the same will happen when creating usernames

Sorry, i meant that it doesn't change anything besides ```varchar``` parsing, so it will break only if someone used the fact that scylla changes ```varchar``` to ```text```.

> OK, so the uppercasing won't matter for table names. But what of the other cases mentioned above? I.e. are indexes, usernames and keyspace names also lowercased later?

Yes, like before. All of them were parsed to data_type and then mapped to lowercase name, so now it has the same result.

2022-07-05 10:28 UTC, kbr- commented
> Sorry, i meant that it doesn't change anything besides varchar parsing, so it will break only if someone used the fact that scylla changes varchar to text.

Ok, but still - please mention all the cases where `varchar` was changed to `text` (username, index, keyspace, and table parsing) in the commit message.

> Yes, like before. All of them were parsed to data_type and then mapped to lowercase name, so now it has the same result.

Before, we used `to_string()` method, which returned lowercase names.
Now, you're using the `type_unreserved_keyword` nonterminal which returns uppercase strings, right?
My question is - are these strings lowercased later? You explained that table names are lowercased (by `set_column_family_name`) but what about the other uses of `unreserved_function_keyword`?

2022-07-05 11:18 UTC, margdoc commented
> Before, we used `to_string()` method, which returned lowercase names. Now, you're using the `type_unreserved_keyword` nonterminal which returns uppercase strings, right? My question is - are these strings lowercased later? You explained that table names are lowercased (by `set_column_family_name`) but what about the other uses of `unreserved_function_keyword`?

I meant that lowercase names are passed to  `set_column_family_name`, so `type_unreserved_keyword` lowercased them.

2022-07-05 11:39 UTC, kbr- approved these changes
LGTM, will merge once CI passes.

2022-07-06 04:10 UTC, closed without merging