Alternator: Add  WCU suppport for update item
scylladb/scylla pull request #21999
Opened 2024-12-19 18:02 UTC by amnonh

This series adds WCU support for the Alternator update item.
This motivation behind it, is to have a rough estimation of what a similar operation would have taken from WCU perspective if used with DynamoDB.

The calculation is done while minimal overhead is the prime objective, the results are values that is less or equal to what it would have been in DynamoDB

** New feature, no need to backport. **

2024-12-20 04:20 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13978/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13978/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: alternator
#### Failed Tests (1/269450):
- [alternator.test_gsi.debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/13978/testReport/junit/%28root%29/non-boost%20tests/alternator_test_gsi_debug_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+alternator.test_gsi.debug.2)
#### Build Details:
- Duration: 10 hr
- Builder: i-0f03d92e32a525cb8 (m5ad.8xlarge)

2024-12-20 22:08 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14005/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14005/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: alternator
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/830/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5565/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2448/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/232/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13578/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14005/)
#### Build Details:
- Duration: 8 hr 42 min
- Builder: spider1.cloudius-systems.com

2025-01-05 16:20 UTC, nyh requested changes
Looks good, I just have some small nitpicks

2025-01-06 07:54 UTC, amnonh commented on test/alternator/test_returnconsumedcapacity.py
> +    val1 = 'a' * (2*KB + 1 - total_length) # val2 is a string that makes the total message length equals to 2KB
The comment is confusing, I want the total length to be 2kb +1

2025-01-06 07:57 UTC, amnonh commented
I've forced push v2 with the changes in the test file

2025-01-06 17:06 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14229/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14229/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: alternator
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/992/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13751/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2625/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5738/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/396/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14229/)
#### Build Details:
- Duration: 9 hr 10 min
- Builder: spider6.cloudius-systems.com

2025-01-13 12:33 UTC, nyh commented on alternator/executor.cc
> +        // ScyllaDB uses two extra bytes compared to DynamoDB for the key bytes length
I thought you'd tell me you have a test that proved it :-) Oh well, I don't have any specific reason to suspect it's not the case. I just thought it's possible that the pk and ck representations are different.

2025-01-13 12:36 UTC, nyh commented
Merged. Thanks.

2025-01-14 12:40 UTC, closed without merging