Add unified tarball to build "ninja"
scylladb/scylla pull request #7260
Opened 2020-09-19 17:58 UTC by yaronkaikov

This pull request adding unified tarball to "ninja" build

2020-09-21 06:45 UTC, penberg requested changes

2020-09-21 06:45 UTC, penberg commented on configure.py
> +        build dist-{mode}: phony dist-server-{mode} dist-python3 dist-tools dist-jmx dist-unified
This is unfortunately not sufficient. The `dist-<mode>` target is supposed to build artifacts just for that target, but `dist-unified` will build the artifacts for _all_ configured build modes. So this change should be `dist-unified-{mode}`, but that build target does not exist (yet) and needs to be added.

2020-09-29 05:34 UTC, yaronkaikov commented
Tested locally with the following commands: 
`./configure.py && ninja dist-dev`
`./configure.py --mode=dev && ninja`
`./configure.py && ninja`

2020-09-29 10:05 UTC, penberg requested changes

2020-09-29 10:05 UTC, penberg commented on configure.py
> +        build dist-unified-tar: phony $builddir/{mode}/scylla-unified-package.tar.gz
This is incorrect. Look at the generated `build.ninja` file:

```
build dist-unified-tar-debug: phony $builddir/debug/scylla-unified-package.tar.gz
build dist-unified-tar-release: phony $builddir/release/scylla-unified-package.tar.gz
build dist-unified-tar-dev: phony $builddir/dev/scylla-unified-package.tar.gz
build dist-unified-tar-sanitize: phony $builddir/sanitize/scylla-unified-package.tar.gz
build dist-unified-tar: phony $builddir/sanitize/scylla-unified-package.tar.gz
```

2020-09-29 10:05 UTC, penberg commented on configure.py
> +        build dist-jmx-tar: phony $builddir/{mode}/dist/tar/scylla-jmx-package.tar.gz
Same here:

```
build dist-jmx-tar: phony $builddir/sanitize/dist/tar/scylla-jmx-package.tar.gz
```

2020-09-29 10:05 UTC, penberg commented on configure.py
> +        build dist-tools-tar: phony $builddir/{mode}/dist/tar/scylla-tools-package.tar.gz
And here:

```
build dist-tools-tar: phony $builddir/sanitize/dist/tar/scylla-tools-package.tar.gz
```

2020-09-29 10:05 UTC, penberg commented on configure.py
> +          command = mkdir -p $builddir/release && ln -f $dir/$artifact $builddir/{mode}/
Why is this change needed? Please note that you also need to fix the `mkdir` path not to be `release` if we do this.

2020-09-29 10:05 UTC, penberg commented on configure.py
> +        build $builddir/{mode}/scylla-python3-package.tar.gz: compat-python3-reloc tools/python3/build/scylla-python3-package.tar.gz
Why is this needed? We don't want to _build_ `scylla-python3-package.tar.gz` multiple times. Instead, we want to build it just once, and *copy* (or make a symlink) it to the `build/<mode>` directories.

2020-09-29 10:05 UTC, penberg commented on configure.py
> +        build dist-python3-tar: phony $builddir/{mode}/dist/tar/scylla-python3-package.tar.gz
This looks incorrect:

```
build dist-python3-tar: phony $builddir/sanitize/dist/tar/scylla-python3-package.tar.gz
```

2020-09-29 11:33 UTC, penberg commented on configure.py
> +        f.write(f'build dist-tools-{mode}: phony $builddir/{mode}/dist/tar/scylla-tools-package.tar.gz dist-tools-rpm dist-tools-deb\n')
It's unfortunate that there's a dependency to `dist-tools-rpm dist-tools-deb`, but that's an existing problem so no need to fix it for this.

2020-09-29 17:57 UTC, closed without merging