hints: fix deleting deleting hint files on drain
scylladb/scylla pull request #8057
Opened 2021-02-09 14:25 UTC by piodul

The send_one_file function works in two modes:

- When the endpoint manager is not draining, it tries to send all hints
  from the file. If some hints fail to be sent, it reports an error. The
  file is deleted if everything was sent successfully.
- When the endpoint manager is draining, it also tries to send all hints
  but it ignores any errors. It always deletes the file at the end.

Another function, send_hints_maybe, calls send_one_file in a loop and
stops after all segments were removed or an error occured. Recently, the
loop condition was modified so that it stops if can_send() returns
false, which could happen if the destination replica is reported in
gossip as DOWN. As send_hints_maybe is used in draining, this could
cause the loop to stop too early and leave some hint files on the disk.
This, in turn, would cause the cleanup to report an error as it tries to
remove a directory which is not completely empty.

To fix this, can_send() was removed from the loop condition. Instead, a
check is added in send_one_file which causes reading from a hints file
to be skipped in case can_send() is false. The logic related to file
removal should work correctly now.

Fixes: #5087
Branches: 4.3, 4.4
Tests:
- unit(dev)
- hinted handoff dtests

2021-02-09 14:40 UTC, avikivity commented
I admit I'm not familiar enough with the code to review (despite the careful explanations), so I'll wait for other reviewers.

2021-02-09 14:47 UTC, psarna approved these changes
Looks reasonable, but @vladzcloudius is more qualified to approve this one.

2021-02-09 23:52 UTC, vladzcloudius commented
@piodul Since this is a regression, please, note the particular patch that have introduced it, which is 

```
commit 77a0f1a153d8d1f694847600e112d6bae38eba04
Author: Piotr Dulikowski <piodul@scylladb.com>
Date:   Mon Oct 12 10:33:59 2020 +0200

    hints: don't read hint files when it's not allowed to send
```

We need this info in order to know where we'll have to backport the fix and it's not only OSS.

2021-02-10 01:33 UTC, vladzcloudius requested changes
I don't like this patch - it doesn't fix the actual problem which is a wrong order of calls here https://github.com/scylladb/scylla/blob/4498bb0a48496c9cdff29364b8dea09d2ba828ee/service/storage_service.cc#L2278-L2279

The code that this patch is trying to "fix" is perfectly fine for a simple reason: "drain" should not be requested until the node is actually removed from the ring.

So, NACK.

2021-03-15 08:31 UTC, haaawk commented
@avikivity I think other reviewers voiced their approvals. Shall we merge the PR?

2021-03-15 08:55 UTC, slivne commented
@haaawk - vlad did not approve the patch - he wrote a comment that its not ok.

2021-03-15 09:16 UTC, haaawk commented
Right. So what's the proposed fix @vladzcloudius ?

2021-03-15 15:29 UTC, vladzcloudius commented
> Right. So what's the proposed fix @vladzcloudius ? Just swap the order of those two calls you've mentioned?

Yes, @haaawk. 
However we need to make sure we don't break other things by doing that.
We'd rather have @asias express his opinion on that.

2021-03-15 17:20 UTC, piodul commented
Sent another PR which swaps the two calls: https://github.com/scylladb/scylla/pull/8284

2021-03-16 10:10 UTC, haaawk commented
can we close his one then? @piodul

2021-03-16 10:18 UTC, closed without merging