tracing: reduce the number of branches to test
scylladb/scylla pull request #8440
Opened 2021-04-09 08:25 UTC by sitano

tracing: reduce the number of branches to test when tracing is disabled.

2021-04-09 08:25 UTC, sitano commented
cc @vladzcloudius whom shall I ping for it?

2021-04-13 15:14 UTC, vladzcloudius requested changes

2021-04-13 15:14 UTC, vladzcloudius commented on transport/server.cc
> +    if (init_trace && trace_state) {
`trace_state` is tested in each of these inline functions. So, I'd expect this optimization not to help much. Do you have benchmarks data to compare?

2021-04-13 16:35 UTC, closed without merging

2021-04-13 17:42 UTC, vladzcloudius commented
> clang is capable of joining consequent checks into 1 if it can prove it does not escape the flow in the middle even in -O1 https://godbolt.org/z/c34nYz74W

Told'ya ;)

2021-04-13 18:39 UTC, slivne commented
CLANG is not necessarily going to stay forever - Avi will consider
switching back once gcc has adequate support.

On Tue, Apr 13, 2021 at 8:43 PM Vladislav Zolotarov <
***@***.***> wrote:

> clang is capable of joining consequent checks into 1 if it can prove it
> does not escape the flow in the middle even in -O1
> https://godbolt.org/z/c34nYz74W
>
> Told'ya ;)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scylladb/scylla/pull/8440#issuecomment-818922863>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2OCCE3VC2HQNZ7LSSVTVDTIR7C7ANCNFSM42UQFPOQ>
> .
>

2021-04-13 23:47 UTC, vladzcloudius commented
On 4/13/21 2:40 PM, Shlomi Livne wrote:
> CLANG is not necessarily going to stay forever - Avi will consider
> switching back once gcc has adequate support.

I'd guess that gcc would do the same optimization here.

>
> On Tue, Apr 13, 2021 at 8:43 PM Vladislav Zolotarov <
> ***@***.***> wrote:
>
> > clang is capable of joining consequent checks into 1 if it can prove it
> > does not escape the flow in the middle even in -O1
> > https://godbolt.org/z/c34nYz74W
> >
> > Told'ya ;)
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > 
> <https://github.com/scylladb/scylla/pull/8440#issuecomment-818922863>, or
> > unsubscribe
> > 
> <https://github.com/notifications/unsubscribe-auth/AA2OCCE3VC2HQNZ7LSSVTVDTIR7C7ANCNFSM42UQFPOQ>
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/scylladb/scylla/pull/8440#issuecomment-818968755>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABOSHLJTFVLJEOURZKV7HBLTISFYJANCNFSM42UQFPOQ>.
>