alternator: Exclusive start key must lie within the segment
scylladb/scylla pull request #9270
Opened 2021-08-31 10:15 UTC by Rjerk

...when using Segment/TotalSegment option.

The requirement is not specified in DynamoDB documents, but found
in DynamoDB Local:

{"__type":"com.amazon.coral.validate#ValidationException",
"message":"Exclusive start key must lie within the segment"}

Signed-off-by: Liu Lan <liulan_yewu@cmss.chinamobile.com>

2021-08-31 11:20 UTC, nyh commented
Thanks!
Next time please open an issue that this PR "Fixes" - the issues are useful for posterity, for release notes, and also to remember to do backports. I'll do it myself this time.

2021-08-31 11:21 UTC, nyh approved these changes

2021-08-31 11:49 UTC, nyh requested changes
1. Please add "Fixes #9272" (the new issue I opened) in the commit message.
2. Real DynamoDB (not DynamoDB Local) prints a different message from what you expected: it prints `The provided starting key is invalid: Invalid ExclusiveStartKey. Please use ExclusiveStartKey with correct Segment. TotalSegments: 1000000 Segment: 0`. So the regular expression you used in the test doesn't match it, and the test fails. You can try this yourself with `pytest --aws test_scan.py::test_scan_parallel_with_exclusive_start_key` in the alternator/test directory.

2021-09-01 02:28 UTC, Rjerk commented
@nyh Done. Fixed the commit message and the test.

2021-09-01 08:21 UTC, nyh approved these changes

2021-09-01 17:21 UTC, closed without merging