cql3: expr: detemplate and deinline find_in_expression() and count_if()
scylladb/scylla pull request #9712
Opened 2021-12-01 05:13 UTC by avikivity

The expression code provides some utilities to examine and manipulate
expressions at prepare time. These are not (or should not be) in the fast
path and so should be optimized for compile time and code footprint
rather than run time.

This series does so by detemplating and deinlining find_in_expression()
and count_if().

2021-12-01 05:16 UTC, avikivity commented
Note: find_in_expression() is mistakenly still used in a fast path, but @cvybhu [promised](https://github.com/scylladb/scylla/pull/9481#issuecomment-982698208) to fix that.

2021-12-02 14:52 UTC, cvybhu commented
Why do we want to deinline those? Shouldn't the compiler be able to decide when to inline stuff?

2021-12-02 15:35 UTC, avikivity commented
> Why do we want to deinline those? Shouldn't the compiler be able to decide when to inline stuff?

So the compiler doesn't have to see them in every translation unit, and recompile any time it changes. These are prepare path operations and not critical.

2021-12-02 16:44 UTC, cvybhu requested changes
Looks ok, although I'm not sure if complicating the code to get a bit quicker compilation is worth it.

The number of instructions increased a bit, but that might go away once `need_filtering()` is moved to prepare time:
```bash
median 34179.54 tps ( 75.1 allocs/op,  12.1 tasks/op,   45944 insns/op)
median 34274.65 tps ( 75.1 allocs/op,  12.1 tasks/op,   46424 insns/op)
# build/release/test/perf/perf_simple_query --cpuset 1 -m 1G --task-quota-ms 10  --random-seed 0 --operations-per-shard 1000000
```

2021-12-02 17:10 UTC, avikivity commented on cql3/expr/expression.cc
> +                if (auto found = recurse_until(op.lhs, predicate_fun)) {
Yes, I kept the changes minimal.

2021-12-02 17:11 UTC, avikivity commented on cql3/expr/expression.cc
> +                if (auto found = recurse_until(op.lhs, predicate_fun)) {
(you're reviewing a code movement patch, not the code changing patch)

2021-12-03 11:24 UTC, psarna approved these changes
Looks good, and btw - @cvybhu compilation times aside, the other important effect of such changes is reduced compiled code size, which also influences performance

2021-12-03 20:51 UTC, closed without merging